foto_album/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include('users.urls')),
    path("", include('fotos.urls')),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fotos/urls.py
from django.urls import path

from . import views

app_name = 'fotos'

urlpatterns = [
    path("", views.galeria, name='galeria'),
    path("agregar/", views.agregar, name="agregar"),
    path("foto/<str:pk>/", views.foto, name="foto"),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('registrarse', views.registrarse, name='registrarse')
]

fotos/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Categoria(models.Model):
    nommbre = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self) -> str:
        return self.nommbre


class Foto(models.Model):
    categoria = models.ForeignKey(
        Categoria, on_delete=models.SET_NULL, null=True, blank=True
    )
    foto = models.ImageField(null=False, blank=False)
    descripcion = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default='1')

    def __str__(self) -> str:
        return self.descripcion

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

# class RegistrarseForm():

fotos/views.py
from unicodedata import category

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .models import Categoria, Foto


# Create your views here.
def galeria(request):
    cat = request.GET.get('categoria')

    if cat == None:
        fotos = Foto.objects.all()
    else:
        fotos = Foto.objects.filter(categoria__nommbre=cat)

    categorias = Categoria.objects.all()
    context = {'categorias': categorias, 'fotos': fotos}
    return render(request, "fotos/galeria.html", context)


def agregar(request):
    categorias = Categoria.objects.all()

    if request.method == 'POST':
        data = request.POST
        imagen = request.FILES.get('foto')

        if data['categoria'] != 'none':
            categoria = Categoria.objects.get(id=data['categoria'])

        elif data['nueva_categoria'] != '':
            categoria, creado = Categoria.objects.get_or_create(
                nommbre=data['nueva_categoria'])

        else:
            categoria = None

        foto = Foto.objects.create(
            categoria=categoria,
            descripcion=data['descripcion'],
            foto=imagen,
        )

        return redirect('fotos:galeria')

    context = {'categorias': categorias}
    return render(request, "fotos/agregar.html", context)


def foto(request, pk):
    foto = Foto.objects.get(id=pk)
    context = {'foto': foto}
    return render(request, "fotos/foto.html", context)

users/views.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


# Create your views here.
def registrarse(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario = form.cleaned_data.get("username")
            messages.success(
                request, f'Bienvenido {usuario}, tu cuenta ha sido registrada'
            )
            return redirect('login')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'users/registrarse.html', context)

fotos/templates/fotos/agregar.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Agregar Foto</title>
{% endblock titulo %}

{% block content %}

<body class="m-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <a class="btn btn-dark my-3" href="{% url 'fotos:galeria' %}">Inicio</a>
                <div class="card">
                    <form method="POST" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group m-3">
                            <label>Descripción</label>
                            <input required name="descripcion" type="text" placeholder="Agrega una descripción"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Categoría</label>
                            <select name="categoria" class="form-control">
                                <option value="none">Selecciona una Categoría</option>
                                {% for categoria in categorias %}
                                    <option value="{{categoria.id}}">{{categoria}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group m-3">
                            <label>Nueva Categoría</label>
                            <input name="nueva_categoria" type="text" placeholder="Nueva Categoría"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Agregar Foto</label>
                            <input required name="foto" type="file" class="form-control-file">
                        </div>

                        <button type="submit" class="btn btn-primary m-3">Agregar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

fotos/templates/fotos/foto.html
{% extends 'base.html' %}

{% block titulo %}
<title>Foto</title>
{% endblock titulo %}

{% block content %}

<body class="m-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <a class="btn btn-dark my-3" href="{% url 'fotos:galeria' %}">Inicio</a>
                <div style="height: 90vh;">
                    <img style="max-width: 100%; max-height: 100%" src="{{foto.foto.url}}" alt="Imagen">
                    <p>{{foto.descripcion}}</p>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

fotos/templates/fotos/galeria.html
{% extends 'base.html' %}

{% block titulo %}
        
    <title>Galeria</title>

{% endblock titulo %}

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block titulo %}
        <title>Index</title>
    {% endblock titulo %}

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <style>
        .image-thumbail {
            height: 200px;
            object-fit: cover;
        }

        .list-group-item a {
            text-decoration: none;
            color: black;
        }
    </style>
</head>

{% block content %}

<body m-5>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="card my-3">
                
                {% if user.is_authenticated %}
                    <div class="card-header">
                        Hola {{user.username}}
                    </div>
                {% else %}
                    <div class="card-header">
                        Categorías
                    </div>
                {% endif %}
                    <ul class="list-group list-group-flush">

                        {% if user.is_authenticated %}
                            <li class="list-group-item logs">
                                <a href="{% url 'logout' %}">Cerrar Sesión</a>
                            </li>
                            <div class="card-header">
                                Categorías
                            </div>
                        {% else %}
                            <li class="list-group-item">
                                <a href="{% url 'users:registrarse' %}">Registrarse</a>
                            </li>
                            <li class="list-group-item">
                                <a href="{% url 'login' %}">Iniciar Sesión</a>
                            </li>
                        {% endif %}
                            <li class="list-group-item">
                                <a href="{% url 'fotos:galeria' %}">Todos</a>
                            </li>
                        {% for categoria in categorias %}
                            <li class="list-group-item">
                                <a href="{% url 'fotos:galeria' %}?categoria={{categoria}}">{{categoria}}</a>
                            </li>
                        {% endfor %}

                        <a class="btn btn-block btn-dark btn-sm m-1" href="{% url 'fotos:agregar' %}">Agregar
                            Foto</a>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                <div class="row">
                    {% for foto in fotos %}
                    <div class="col-md-4 card my-3">
                        <img class="image-thumbail" src="{{foto.foto.url}}" alt="Imagen">
                        <div class="card-body">
                            <small>Categoria: {{foto.categoria}}</small> <br>
                            <small>Usuario: {{foto.owner}}</small>
                        </div>
                        <a class="btn btn-outline-dark btn-sm m-1" href="{% url 'fotos:foto' foto.id %}">Ver</a>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
{% endblock content %}

</html>

users/templates/users/login.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Log In</title>
{% endblock titulo %}

{% block content %}

<br>
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-4">
            <div class="card">
                <div class="card-header bg-dark bg-gradient bg-opacity-50">
                    <div class="card-title">
                        Iniciar Sesión
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for campo in form %}
                            <div class="form-group">
                                {{campo.name}}
                                <br>
                                {{campo}}
                            </div>
                        {% endfor %}
                        <br>
                        <button class="btn btn-outline-dark" type="submit">Iniciar Sesión</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Log Out</title>
{% endblock titulo %}

{% block content %}
    <div class="alert alert-danger" role="alert">
        Has Cerrado Sesión!
    </div>
    <div>
        <a class="btn btn-outline-dark btn-sm m-1" href="{% url 'fotos:galeria' %}">Inicio</a>
    </div>
{% endblock content %}

users/templates/users/registrarse.html
{% extends 'base.html' %}

{% block titulo %}
<title>Registro</title>
{% endblock titulo %}

{% block content %}

<body class="m-5">
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-4">
                <div class="card">
                    <div class="card-header bg-dark bg-gradient bg-opacity-50">
                        <div class="card-title">
                            Iniciar Sesión
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for campo in form %}
                                <div class="form-group">
                                    {{campo.name}}
                                    <br>
                                    {{campo}}
                                </div>
                            {% endfor %}
                            <br>
                            <button class="btn btn-outline-dark" type="submit">Registrarse</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}